modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/NotableBubbleText/issues"
license="MIT"

[[mods]]
modId="nbt"
version="${file.jarVersion}"
displayName="Notable Bubble Text"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nbt"
authors="Mrbysco, ShyNieke"
description='''
I'm going to bubble your text and there's nothing you can do about it.
'''
[[dependencies.nbt]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"